# Generated by Django 3.1.5 on 2021-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('titulo_original', models.CharField(blank=True, max_length=300, null=True)),
                ('sinopse', models.TextField()),
                ('nota', models.IntegerField(blank=True, default=0)),
                ('capa', models.ImageField(upload_to='media/capas')),
            ],
        ),
    ]
