# Generated by Django 3.1.5 on 2021-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='assistido_por',
            field=models.ManyToManyField(blank=True, related_name='usuariso_assistidos', to='perfis.Perfil'),
        ),
    ]
