# Generated by Django 3.1.5 on 2021-02-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_auto_20210203_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='num_temporadas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
