# Generated by Django 3.1.5 on 2021-02-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_anime_num_temporadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='num_ep',
        ),
        migrations.AddField(
            model_name='anime',
            name='num_ep_temporada',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='num_toal_ep',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
