# Generated by Django 3.1.5 on 2021-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0008_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
