# Generated by Django 3.1.5 on 2021-01-21 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('assistidos', models.ManyToManyField(blank=True, related_name='assistidos', to='animes.Anime')),
                ('favoritos', models.ManyToManyField(blank=True, related_name='favoritos', to='animes.Anime')),
                ('quero_ver', models.ManyToManyField(blank=True, related_name='quero_ver', to='animes.Anime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
