# Generated by Django 3.1.5 on 2021-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='total_assistidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
