# Generated by Django 3.1.5 on 2021-01-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfil_total_assistidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='total_favoritos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
