# Generated by Django 3.1.5 on 2021-01-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_total_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='total_quero_ver',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
