# Generated by Django 3.1.5 on 2021-01-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_perfil_total_quero_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='total_assistidos',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='total_favoritos',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='total_quero_ver',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
