# Generated by Django 3.1.5 on 2021-01-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_auto_20210121_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='github',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
