# Generated by Django 3.1.5 on 2021-01-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_auto_20210121_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='total_assistidos',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='total_favoritos',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='total_quero_ver',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='profiles-pics'),
        ),
    ]
